# Verstappen Theme — Hyprland

general {
    col.active_border   = rgb(e8002d) rgb(ffd700) 45deg
    col.inactive_border = rgb(1e2d50)
}

decoration {
    rounding = 6
    shadow {
        color        = rgba(e8002d33)
        color_inactive = rgba(0a0e1a99)
    }
}
